#!/bin/sh
set -e
if [ "$1" = "purge" ]; then
    userdel powpow 2>/dev/null || true
    groupdel powpow 2>/dev/null || true
fi
if [ "$1" = "purge" ] || [ "$1" = "remove" ]; then
    systemctl daemon-reload
fi
